### ISSUE TITLE
Automatic email sending upon class based createview, updateview 

### ISSUE THREAD

**Issue by sunjoomoon** [peopledoc/django-mail-factory#62]
Following https://docs.djangoproject.com/en/1.8/topics/class-based-views/generic-editing/ 
# views.py

```
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from myapp.models import Author

class AuthorCreate(CreateView):
    model = Author
    fields = ['name','email']

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['name','email']

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('author-list')
```

I am trying to figure out how mail-factory can be used to send email  to the  user's 'email' field and to 'settings.MANAGERS' upon Author creation and Update. Any example or hint will be cool.

**Comment by EnriqueSoria** [comment]
You can use [Django Signals](https://docs.djangoproject.com/en/3.0/topics/signals/)

**Comment by ewjoachim** [comment]
Hello :)

So did it work for your usecase ? If so, and you think this should be somewhere in the documentation, would you be interesting in providing a pull request and add it ? If not, is it OK if we close the ticket ?

Thank you :)

**Comment by ewjoachim** [comment]
I'll close for now but that does not mean we're not interested in feedback. If there's anything you find still needs discussing, by all means, reopen.
